// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkGBJyQj3V9vRiswawgNo_ELDIO7nhboo',
    appId: '1:94109248921:web:975284bf507f17bcc5f708',
    messagingSenderId: '94109248921',
    projectId: 'hsi-project-88352',
    authDomain: 'hsi-project-88352.firebaseapp.com',
    storageBucket: 'hsi-project-88352.firebasestorage.app',
    measurementId: 'G-5RH8DBCJY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArCdGI-spz5Z7tQFLp-5dp8yf6WgrE0-k',
    appId: '1:94109248921:android:ee3ca6ce5994a36bc5f708',
    messagingSenderId: '94109248921',
    projectId: 'hsi-project-88352',
    storageBucket: 'hsi-project-88352.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDP31FRvLsTDGqLKavIGXdmrJX1GTabxoo',
  //   appId: '1:94109248921:ios:393b75d8b76d7397c5f708',
  //   messagingSenderId: '94109248921',
  //   projectId: 'hsi-project-88352',
  //   storageBucket: 'hsi-project-88352.firebasestorage.app',
  //   iosBundleId: 'com.example.hsi',
  // );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP31FRvLsTDGqLKavIGXdmrJX1GTabxoo',
    appId: '1:94109248921:ios:393b75d8b76d7397c5f708',
    messagingSenderId: '94109248921',
    projectId: 'hsi-project-88352',
    storageBucket: 'hsi-project-88352.firebasestorage.app',
    iosBundleId: 'com.example.hsi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkGBJyQj3V9vRiswawgNo_ELDIO7nhboo',
    appId: '1:94109248921:web:1897a68d1ed5cee7c5f708',
    messagingSenderId: '94109248921',
    projectId: 'hsi-project-88352',
    authDomain: 'hsi-project-88352.firebaseapp.com',
    storageBucket: 'hsi-project-88352.firebasestorage.app',
    measurementId: 'G-JQSG5Q1E90',
  );
}
